<a href="https://colab.research.google.com/github/skimaza/AIRI400/blob/master/tensor_%EB%A9%98%ED%86%A0%EB%A7%81_%EC%9E%90%EB%A3%8C_0729.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 참고 문서
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

Deep Learning with PyTorch

In [20]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [21]:
from __future__ import print_function
import torch

In [22]:
x = torch.empty(5, 3) # 5행, 3열의 텐서. 값은 모두 garbage
print(x)

tensor([[2.7657e+09, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [4.4721e+21, 1.5956e+25, 4.7399e+16],
        [3.7987e-39, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [23]:
print(x.size()) # size, shape

torch.Size([5, 3])


In [24]:
print(x.shape)

torch.Size([5, 3])


Python List vs Tensor

![](https://drive.google.com/uc?export=view&id=1iAUKkpqT8-h3TF0ghB6Td9WCvn0s6Of7)



<div class="alert alert-info"><h1>Uninitialized vs random</h1><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>


---




Construct a 5x3 matrix, uninitialized:

즉 값이 garbage임. random이 아님.



In [25]:
x = torch.empty(5, 3)
print(x)

tensor([[2.7657e+09, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [4.4721e+21, 1.5956e+25, 4.7399e+16],
        [3.7293e-08, 2.4209e+24, 4.1996e+12],
        [7.5338e+28, 1.5975e-43, 0.0000e+00]])


In [26]:
print(torch.get_default_dtype())

torch.float32


In [27]:
print(x.dtype)

torch.float32


torch.empty는 torch의 global default dtype 이면서 garbage 값을 가지는 원소가 채워진 텐서를 생성.

즉 디폴트 타입을 갖는 빈 텐서를 생성.

In [28]:
x = torch.FloatTensor(5,3)
print(x)

tensor([[2.7657e+09, 0.0000e+00, 2.1019e-44],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [4.4721e+21, 1.5956e+25, 4.7399e+16],
        [3.7987e-39, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


torch.FloatTensor 도 torch.float32 타입의 텐서를 생성.



---


tensor types

![](https://drive.google.com/uc?export=view&id=1gYaex7yAnPhfTh1tvsxTwsMLht74ozSw)

<h1>주의) torch.Tensor와 torch.tensor 사용 예.</h1>

torch.Tensor는 Tensor 클래스를 instantiation. 즉 torch.empty와 같은 동작.

torch.tensor는 인자로 받는 데이터 값을 복제. 인자는 리스트, 튜플, ndarray, 스칼라 값 등 다양한 형태. 텐서를 만드는 가장 일반적 형태임.

In [29]:
x = torch.Tensor(5,3)
print(x, x.dtype) # 의미없는 값.

tensor([[2.7656e+09, 0.0000e+00, 2.1019e-44],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.8314e+25, 6.9768e+22, 2.7708e+20],
        [2.2945e+02, 5.0664e+07, 3.9760e+12],
        [1.0333e+18, 0.0000e+00, 0.0000e+00]]) torch.float32


In [30]:
x = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
print(x, x.dtype)

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]]) torch.float32


In [31]:
x = torch.tensor([0, 1]) # dtype을 인자의 값에서 유추하여 설정
print(x, x.dtype) 

tensor([0, 1]) torch.int64


In [32]:
y = torch.tensor([0.0, 1.0])
print(y, y.dtype)

tensor([0., 1.]) torch.float32


In [33]:
z = torch.tensor([[0.11111, 0.222222, 0.3333333]], dtype=torch.float64, device=torch.device('cuda:0'))  # creates a torch.cuda.DoubleTensor
print(z, z.dtype)

tensor([[0.1111, 0.2222, 0.3333]], device='cuda:0', dtype=torch.float64) torch.float64


CPU 환경에선 위 문장이 오류 발생.

GPU 환경으로 런타임 변경 후 실행.



In [34]:
x = torch.tensor(3.14159)  # Create a scalar (zero-dimensional tensor)
print(x, x.dtype)

tensor(3.1416) torch.float32


In [35]:
x = torch.tensor([])  # Create an empty tensor (of size (0,))
print(x, x.dtype)

tensor([]) torch.float32


In [36]:
#x = torch.tensor(3,2) # 인자가 매치하지 않으므로 오류가 나야 함.
#print(x, x.dtype)



---



<h1>Random</h1>
Construct a randomly initialized matrix:



In [37]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6901, 0.5737, 0.1355],
        [0.9151, 0.9049, 0.4126],
        [0.3773, 0.4832, 0.0362],
        [0.6622, 0.1474, 0.1550],
        [0.4327, 0.1972, 0.4039]])


Construct a matrix filled zeros and of dtype long:



In [38]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


<h1>데이터를 인자로 주어 텐서 생성</h1>
Construct a tensor directly from data:



In [39]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [40]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x, x.dtype)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x, x.dtype)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.float64
tensor([[ 6.2149e-02,  1.1317e+00, -2.8233e-02],
        [-1.0532e-01, -3.1601e-01,  1.6695e+00],
        [ 1.5377e+00, -2.7045e-01,  1.6972e+00],
        [ 2.5579e-01, -1.4533e+00,  1.3298e+00],
        [-1.0005e+00, -4.4373e-04, -2.2297e-02]]) torch.float32


Get its size: size() or shape



In [41]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

<h1>텐서 더하기</h1>

Addition: syntax 1



In [42]:
y = torch.rand(5, 3)
print('x\n', x)
print('y\n', y)
print('x+y\n', x + y)

x
 tensor([[ 6.2149e-02,  1.1317e+00, -2.8233e-02],
        [-1.0532e-01, -3.1601e-01,  1.6695e+00],
        [ 1.5377e+00, -2.7045e-01,  1.6972e+00],
        [ 2.5579e-01, -1.4533e+00,  1.3298e+00],
        [-1.0005e+00, -4.4373e-04, -2.2297e-02]])
y
 tensor([[0.5124, 0.4810, 0.6813],
        [0.1825, 0.9091, 0.9435],
        [0.2758, 0.3931, 0.0245],
        [0.9753, 0.6355, 0.2483],
        [0.7985, 0.4970, 0.2984]])
x+y
 tensor([[ 0.5745,  1.6128,  0.6530],
        [ 0.0772,  0.5931,  2.6130],
        [ 1.8135,  0.1226,  1.7216],
        [ 1.2311, -0.8178,  1.5782],
        [-0.2020,  0.4966,  0.2761]])


Addition: syntax 2



In [43]:
print(torch.add(x, y))

tensor([[ 0.5745,  1.6128,  0.6530],
        [ 0.0772,  0.5931,  2.6130],
        [ 1.8135,  0.1226,  1.7216],
        [ 1.2311, -0.8178,  1.5782],
        [-0.2020,  0.4966,  0.2761]])


Addition: providing an output tensor as argument



In [44]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)
res = x + y
print(res)

tensor([[ 0.5745,  1.6128,  0.6530],
        [ 0.0772,  0.5931,  2.6130],
        [ 1.8135,  0.1226,  1.7216],
        [ 1.2311, -0.8178,  1.5782],
        [-0.2020,  0.4966,  0.2761]])
tensor([[ 0.5745,  1.6128,  0.6530],
        [ 0.0772,  0.5931,  2.6130],
        [ 1.8135,  0.1226,  1.7216],
        [ 1.2311, -0.8178,  1.5782],
        [-0.2020,  0.4966,  0.2761]])


Addition: in-place



In [45]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.5745,  1.6128,  0.6530],
        [ 0.0772,  0.5931,  2.6130],
        [ 1.8135,  0.1226,  1.7216],
        [ 1.2311, -0.8178,  1.5782],
        [-0.2020,  0.4966,  0.2761]])


# **_로 끝나는 operation은 in-place**
<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!





# Indexing tensors

## Python slicing 과 유사

![](https://drive.google.com/uc?export=view&id=1MqqMAPVwlE4QcXZRrlHBLBFNvUNQNBj-)


In [46]:
some_list = list(range(6))
some_list[:]

[0, 1, 2, 3, 4, 5]

In [47]:
print(some_list[1:4])
print(some_list[1:])
print(some_list[:4])
print(some_list[:-1])
print(some_list[1:4:2]) # 1 to 3 ([1,2,3]), step 2 ([1,3])

[1, 2, 3]
[1, 2, 3, 4, 5]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[1, 3]


In [48]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [49]:
print(points[1:])

tensor([[5., 3.],
        [2., 1.]])


In [50]:
print(points[1:, :])

tensor([[5., 3.],
        [2., 1.]])


In [51]:
print(points[1:, 0])

tensor([5., 2.])


In [52]:
print(points[None])

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


In [53]:
print(points[None].size())

torch.Size([1, 3, 2])


In [54]:
print(points.unsqueeze(dim=0), points.unsqueeze(dim=0).size())

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]]) torch.Size([1, 3, 2])


In [55]:
print(x)
print(x[:, 1])

tensor([[ 6.2149e-02,  1.1317e+00, -2.8233e-02],
        [-1.0532e-01, -3.1601e-01,  1.6695e+00],
        [ 1.5377e+00, -2.7045e-01,  1.6972e+00],
        [ 2.5579e-01, -1.4533e+00,  1.3298e+00],
        [-1.0005e+00, -4.4373e-04, -2.2297e-02]])
tensor([ 1.1317e+00, -3.1601e-01, -2.7045e-01, -1.4533e+00, -4.4373e-04])




---

Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [56]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print('x.size()=', x.size(), '\ny.size()=', y.size(), '\nz.size()=', z.size())
print(x, '\n', y, '\n', z)

x.size()= torch.Size([4, 4]) 
y.size()= torch.Size([16]) 
z.size()= torch.Size([2, 8])
tensor([[ 0.1271, -2.2375,  1.5773,  0.0976],
        [-0.9709,  1.2337,  1.9824,  1.2391],
        [ 0.9222, -1.6150,  1.0503,  1.3855],
        [-0.1771,  0.5662,  0.6928,  0.2521]]) 
 tensor([ 0.1271, -2.2375,  1.5773,  0.0976, -0.9709,  1.2337,  1.9824,  1.2391,
         0.9222, -1.6150,  1.0503,  1.3855, -0.1771,  0.5662,  0.6928,  0.2521]) 
 tensor([[ 0.1271, -2.2375,  1.5773,  0.0976, -0.9709,  1.2337,  1.9824,  1.2391],
        [ 0.9222, -1.6150,  1.0503,  1.3855, -0.1771,  0.5662,  0.6928,  0.2521]])




---
저장 형태


![](https://drive.google.com/uc?export=view&id=1wmqtH9XucnuGg11_a_oK9kODDH_C7nZI)

In [57]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)
points.storage()

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [58]:
p2 = points.view(2,3)
print(p2)
print(p2.storage())

tensor([[4., 1., 5.],
        [3., 2., 1.]])
 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]


# 주의 사항
storage() 함수는 일반적 함수가 아니며 호환성이 보장되지 않음. 즉 언제든 없어질 수 있음.
여기서는 파이토치 텐서 구조를 이해하기 위해 사용하고 있는 것임.

또 storage()로 구한 어레이의 값을 바꾸는 것도 위험한 일임.

In [59]:
points_storage = points.storage()
print(points_storage)

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]


In [60]:
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])



---
# Tensor metadata


![](https://drive.google.com/uc?export=view&id=1n0onCe209LOMfGvdYYn9DQVcLJ5Kv7_5)

In [61]:
points = torch.tensor([[5,7,4],[1,3,2],[7,3,8]])
points.storage()

 5
 7
 4
 1
 3
 2
 7
 3
 8
[torch.LongStorage of size 9]

In [62]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points)
print(points.storage())
print(points.storage_offset())

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]
0


In [63]:
second_point = points[1]
print('second_point', second_point)
print('storage_offset()', second_point.storage_offset())
print('points[1].storage_offset()', points[1].storage_offset())


second_point tensor([5., 3.])
storage_offset() 2
points[1].storage_offset() 2


##second_point는 데이터가 복사된 것이 아니라 메타데이터만 바뀐 것임

In [64]:
print(points.size())
print(points.stride())

torch.Size([3, 2])
(2, 1)


In [65]:
print(second_point.size())
print(second_point.stride())

torch.Size([2])
(1,)


In [66]:
print(points.stride())

(2, 1)


In [67]:
print(second_point.shape)

torch.Size([2])


##데이터 액세스는 offset, stride를 이용하여 위치를 계산.

2D tensor [i, j] element access

storage_offset + stride[0] * i + stride[1] * j

In [68]:
storage = points.storage()
storage_offset = points.storage_offset()
stride = points.stride()
print(storage, storage_offset, stride)
print(points[2, 1])


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6] 0 (2, 1)
tensor(1.)


In [69]:
print(storage[storage_offset + stride[0] * 2 + stride[1] * 1])

1.0


## storage를 변경하면 원래 텐서도 바뀐다
## 이렇게 사용하는 것은 권장되지 않는 방법이고 이해를 위해 storage를 설명한 것임


In [70]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

## second_point 뿐 아니라 points도 바뀜

---

## clone을 쓰면 storage를 복사한다

In [71]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

---
# transpose

![](https://drive.google.com/uc?export=view&id=1oI0ZelEcsTW_iztuXYCsUFL6Mnj3fLb9)

In [72]:
points = torch.tensor([[3.0, 1.0, 2.0], [4.0, 1.0, 7.0]])
print(points)

tensor([[3., 1., 2.],
        [4., 1., 7.]])


## 서로 바꿀 두 디멘션을 지정

In [73]:
points_tr = points.transpose(0, 1)

In [74]:
points_tr

tensor([[3., 4.],
        [1., 1.],
        [2., 7.]])

In [75]:
print(points_tr.storage())
print(points.stride())
print(points_tr.stride())

 3.0
 1.0
 2.0
 4.0
 1.0
 7.0
[torch.FloatStorage of size 6]
(3, 1)
(1, 3)


In [76]:
points

tensor([[3., 1., 2.],
        [4., 1., 7.]])

In [78]:
points_t = points.t() # 2D or less dimension
print(points_t)

tensor([[3., 4.],
        [1., 1.],
        [2., 7.]])


In [86]:
points.storage()

 3.0
 1.0
 2.0
 4.0
 1.0
 7.0
[torch.FloatStorage of size 6]

In [85]:
points_t.storage()

 3.0
 1.0
 2.0
 4.0
 1.0
 7.0
[torch.FloatStorage of size 6]

In [92]:
print(points.storage(), points)

 3.0
 1.0
 2.0
 4.0
 1.0
 7.0
[torch.FloatStorage of size 6] tensor([[3., 1., 2.],
        [4., 1., 7.]])


In [88]:
points.stride()

(3, 1)

In [93]:
points_t

tensor([[3., 4.],
        [1., 1.],
        [2., 7.]])

In [89]:
points_t.stride()

(1, 3)

![](https://drive.google.com/uc?export=view&id=1oI0ZelEcsTW_iztuXYCsUFL6Mnj3fLb9)

## Multidimensional

In [94]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2) # 0번째와 2번째 디멘션을 transpose
some_t.shape

torch.Size([3, 4, 5])

In [95]:
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [97]:

transpose_t.shape


torch.Size([5, 4, 3])

In [98]:

some_t.stride()


(20, 5, 1)

In [99]:

transpose_t.stride()


(1, 5, 20)

# Contiguous

가장 오른쪽 차원이 순차적으로 저장된 텐서

In [100]:
some_t.is_contiguous()

True

In [101]:
transpose_t.is_contiguous()

False

## Contiguous로 변환하기

In [108]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [109]:
points_t = points.t()

In [110]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [111]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [112]:
points_t.stride()

(1, 2)

In [113]:
points_t_cont = points_t.contiguous()

In [114]:
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [115]:
points_t_cont.stride()

(3, 1)

In [116]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

## tensor view()

같은 storage 에서 보는 관점 (shape)만 다르게 함

In [124]:
t = torch.rand(4, 4)
b = t.view(2, 8)
print(t, t.shape)
print(b, b.shape)

tensor([[0.2186, 0.3878, 0.2338, 0.3695],
        [0.8055, 0.0071, 0.1975, 0.3930],
        [0.2079, 0.6703, 0.9268, 0.6448],
        [0.0171, 0.0831, 0.4419, 0.9077]]) torch.Size([4, 4])
tensor([[0.2186, 0.3878, 0.2338, 0.3695, 0.8055, 0.0071, 0.1975, 0.3930],
        [0.2079, 0.6703, 0.9268, 0.6448, 0.0171, 0.0831, 0.4419, 0.9077]]) torch.Size([2, 8])


In [125]:
print(t.stride(), b.stride())

(4, 1) (8, 1)


In [126]:
t.is_contiguous()

True

In [127]:
b.is_contiguous()

True

In [131]:
print(t.storage())
print('------------------')
print(b.storage())

 0.21861666440963745
 0.38779711723327637
 0.23383945226669312
 0.36954402923583984
 0.8054532408714294
 0.007084488868713379
 0.19748222827911377
 0.3930157423019409
 0.2078811526298523
 0.6703256964683533
 0.9267706274986267
 0.644775390625
 0.017052173614501953
 0.08314478397369385
 0.44186484813690186
 0.9077044129371643
[torch.FloatStorage of size 16]
------------------
 0.21861666440963745
 0.38779711723327637
 0.23383945226669312
 0.36954402923583984
 0.8054532408714294
 0.007084488868713379
 0.19748222827911377
 0.3930157423019409
 0.2078811526298523
 0.6703256964683533
 0.9267706274986267
 0.644775390625
 0.017052173614501953
 0.08314478397369385
 0.44186484813690186
 0.9077044129371643
[torch.FloatStorage of size 16]


## view 같은 operation은 contiguous tensor에서만 동작

In [136]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [133]:
x.shape

torch.Size([2, 3])

In [134]:
x_t = x.t()
x_t

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [135]:
y = x.view(3,2) # transpose가 아님
y

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [137]:
y.is_contiguous()

True

In [138]:
x_t.is_contiguous()

False

In [139]:
# x_t.view(2, 3) # error

RuntimeError: ignored

In [143]:
x_t_cont = x_t.contiguous()
x_t_cont

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [144]:
x_t_cont.view(2, 3)

tensor([[1, 4, 2],
        [5, 3, 6]])

In [145]:
x_t

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [146]:
x = torch.randn(2,3,4)
x_t = x.transpose(0, 2)
print(x.shape)
print(x_t.shape)


torch.Size([2, 3, 4])
torch.Size([4, 3, 2])


In [147]:
x

tensor([[[ 1.2233, -0.7113,  0.6238, -1.6227],
         [-1.8547, -0.2439, -0.3427,  1.1804],
         [-0.3687,  0.6420, -0.0362,  0.3887]],

        [[-1.4247, -0.0020, -1.1433, -0.2288],
         [-0.6830, -1.4532,  0.4469, -0.4412],
         [ 0.5310,  0.5736, -1.3420, -1.0743]]])

In [148]:
x.view(2, 12)

tensor([[ 1.2233, -0.7113,  0.6238, -1.6227, -1.8547, -0.2439, -0.3427,  1.1804,
         -0.3687,  0.6420, -0.0362,  0.3887],
        [-1.4247, -0.0020, -1.1433, -0.2288, -0.6830, -1.4532,  0.4469, -0.4412,
          0.5310,  0.5736, -1.3420, -1.0743]])

In [ ]:
# x_t.view(4,6) # Error

RuntimeError: ignored

## slicing

In [149]:
x = torch.tensor([[[1, 2, 3, 4, 5], [6,7,8,9,10], [11,12,13,14,15]], [[16, 17, 18, 19, 20], [21,22,23,24,25], [26,27,28,29,30]]])

In [150]:
print(x.shape)
print(x.storage())
x

torch.Size([2, 3, 5])
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29
 30
[torch.LongStorage of size 30]


tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]],

        [[16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]])

In [151]:
x[1:]

tensor([[[16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]])

In [152]:
x[0]

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [153]:
x[0, 1:]

tensor([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [154]:
x[0, 1:, 0:4]

tensor([[ 6,  7,  8,  9],
        [11, 12, 13, 14]])

In [155]:
x[0, 1:, 1:3]

tensor([[ 7,  8],
        [12, 13]])

In [156]:
x[0, 1:, 0:3:2]

tensor([[ 6,  8],
        [11, 13]])

In [157]:
x[0, 1:, 1:3:2]

tensor([[ 7],
        [12]])

In [158]:
x

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]],

        [[16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]])

In [159]:
y = torch.rand(3,4,5)
y

tensor([[[0.3761, 0.7538, 0.8425, 0.4088, 0.5789],
         [0.3466, 0.1129, 0.5182, 0.8586, 0.0832],
         [0.0205, 0.3271, 0.8146, 0.6796, 0.0812],
         [0.9901, 0.6523, 0.1598, 0.3822, 0.5773]],

        [[0.0296, 0.4886, 0.1073, 0.6267, 0.9024],
         [0.4118, 0.2284, 0.2984, 0.6761, 0.6500],
         [0.1761, 0.5419, 0.2516, 0.0395, 0.6175],
         [0.6309, 0.2511, 0.0536, 0.1153, 0.3009]],

        [[0.8316, 0.1818, 0.3634, 0.7148, 0.8096],
         [0.7412, 0.4476, 0.3727, 0.8049, 0.9054],
         [0.7750, 0.3089, 0.7294, 0.8671, 0.1742],
         [0.8533, 0.0967, 0.2887, 0.8885, 0.1471]]])

In [160]:
z = y[0, 2:, 1:7:2]
z

tensor([[0.3271, 0.6796],
        [0.6523, 0.3822]])

In [161]:
y.is_contiguous()

True

In [162]:
z.is_contiguous()

False

In [163]:
z = y[1, 2, :]
z

tensor([0.1761, 0.5419, 0.2516, 0.0395, 0.6175])

In [164]:
z.is_contiguous()

True

In [169]:
z = y[0, 2, 1:3]
print(z)
print(z.stride())
print(z.size())
print(z.is_contiguous())

tensor([0.3271, 0.8146])
(1,)
torch.Size([2])
True


In [168]:
z = y[0, 2:, 1:3]
print(z)
print(z.stride())
print(z.size())
print(z.is_contiguous())

tensor([[0.3271, 0.8146],
        [0.6523, 0.1598]])
(5, 1)
torch.Size([2, 2])
False


##Break

---

## reshape()

In [ ]:
print(x.size())
x

torch.Size([2, 3, 5])


tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]],

        [[16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]])

In [ ]:
y = x.reshape((6, 5))

In [ ]:
print(y.size())
y

torch.Size([6, 5])


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]])

In [ ]:
z = x.reshape((6, -1))

In [ ]:
z

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]])

In [ ]:
z.stride()

(5, 1)

In [ ]:
z = x.reshape((3, -1))

In [ ]:
z

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
z.stride()

(10, 1)

In [ ]:
y = x.reshape((-1, 10))

In [ ]:
y

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
y = x.reshape((-1, 5))

In [ ]:
y

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]])

In [ ]:
y.is_contiguous()

True

In [ ]:
y.stride()

(5, 1)

In [ ]:
x.shape

torch.Size([2, 3, 5])

In [ ]:
# y = x.reshape(7, -1) # error!

RuntimeError: ignored

In [ ]:
# y = x.reshape(-1, -1) # error

RuntimeError: ignored

In [ ]:
y = x.reshape(1, -1)

In [ ]:
y.shape

torch.Size([1, 30])

## torch.squeeze()

원소 1개짜리 디멘션 제거

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()


torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x)
y.size()


torch.Size([2, 2, 2])

In [ ]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x, 0) # dim 0 만 squeeze
y.size()


torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [ ]:
y = x.squeeze()
y.size()

torch.Size([2, 2, 2])

In [ ]:
y = x.squeeze(1)
y.size()

torch.Size([2, 2, 1, 2])

## unsqueeze()

원소 1개짜리 디멘션 추가

In [ ]:
x = torch.tensor([1, 2, 3, 4])
y = torch.unsqueeze(x, 0)
print(x)
print(y)

tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])


In [ ]:
z = torch.unsqueeze(x, 1)
z

tensor([[1],
        [2],
        [3],
        [4]])

## expand(), expand_as()

원소 1개짜리 디멘션을 더 큰 디멘션으로 확장

In [ ]:
x = torch.tensor([[1], [2], [3]])
print(x)
x.size()

tensor([[1],
        [2],
        [3]])


torch.Size([3, 1])

In [ ]:
y = x.expand(3, 4)
print(y)
print(y.size())

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])
torch.Size([3, 4])


In [ ]:
z = x.expand(-1, 4)   # -1 means not changing the size of that dimension
print(z)
print(z.size())

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])
torch.Size([3, 4])


In [ ]:
other = torch.rand(3,4)

In [ ]:
other.size()

torch.Size([3, 4])

In [ ]:
y = x.expand_as(other)

In [ ]:
y

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [ ]:
y.size()

torch.Size([3, 4])

## break

## narrow(dim, start, length)

dim : 줄일 디멘션
start : 시작
length : 개수

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x, x.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]), torch.Size([3, 3]))

In [ ]:
y = torch.narrow(x, 0, 0, 2)
y


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
y = torch.narrow(x, 0, 1, 2)
y


tensor([[4, 5, 6],
        [7, 8, 9]])

In [ ]:
z = torch.narrow(x, 1, 0, 1)
z

tensor([[1],
        [4],
        [7]])

In [ ]:
print(x.narrow(1, 1, 2))
print(x.narrow(1, 1, 1))
print(x.narrow(1, 2, 1))

tensor([[2, 3],
        [5, 6],
        [8, 9]])
tensor([[2],
        [5],
        [8]])
tensor([[3],
        [6],
        [9]])


In [ ]:
z = torch.narrow(x, 1, 1, 2)
z

tensor([[2, 3],
        [5, 6],
        [8, 9]])

In [ ]:
z = x.narrow(1, 2, 1)
z

tensor([[3],
        [6],
        [9]])

## diagonal()

In [ ]:
a = torch.randn(3, 3)
a


tensor([[-0.6232, -0.6693,  1.3066],
        [-0.3225,  0.2180, -0.1333],
        [ 0.5751, -0.7314, -0.3579]])

In [ ]:
d = torch.diagonal(a, 0)
d

tensor([-0.6232,  0.2180, -0.3579])

In [ ]:
d_above = torch.diagonal(a, 1)
d_above

tensor([-0.6693, -0.1333])

In [ ]:
d_below = torch.diagonal(a, -1)
d_below

tensor([-0.3225, -0.7314])

In [ ]:
a = torch.randn(4,4)
a

tensor([[-0.9769,  0.9301, -0.6780,  0.1816],
        [ 1.3444, -0.9669,  0.5290, -0.3743],
        [-1.4539, -1.4204,  0.0076,  0.6739],
        [ 1.4391, -0.3722, -1.3122, -0.9337]])

In [ ]:
a.diagonal(1)

tensor([0.9301, 0.5290, 0.6739])

In [ ]:
a.diagonal(2)

tensor([-0.6780, -0.3743])

In [ ]:
a.diagonal(3)

tensor([0.1816])

In [ ]:
a.diagonal(4)

tensor([])

In [ ]:
a.diagonal(5), a.diagonal(6).size()

(tensor([]), torch.Size([0]))

In [ ]:
x = torch.randn(2, 5, 4)
print(x)

tensor([[[ 1.9961e-03,  2.6247e-01, -2.9922e-01, -3.8175e-01],
         [-1.7990e+00, -1.2441e+00,  2.4032e-01,  4.7539e-01],
         [ 3.6852e-01,  1.3100e+00, -2.6040e-01, -4.8632e-01],
         [-5.1233e-01, -3.8668e-01,  1.3594e+00, -1.2349e+00],
         [ 1.2196e+00, -5.2522e-01,  4.1797e-01, -5.8621e-01]],

        [[ 4.6535e-01, -7.2585e-01,  1.5041e+00,  5.7029e-02],
         [-1.0932e+00,  8.0494e-02, -3.0155e-01, -1.5572e+00],
         [ 1.2115e+00, -6.2522e-01, -1.5306e+00, -1.0598e+00],
         [-9.7102e-01, -6.3096e-01, -6.9881e-02,  3.5901e-01],
         [ 1.6594e-01,  2.3821e+00, -1.7571e-01,  4.4202e-01]]])


In [ ]:
x_diag = torch.diagonal(x)
x_diag

tensor([[ 0.0020, -1.0932],
        [ 0.2625,  0.0805],
        [-0.2992, -0.3016],
        [-0.3818, -1.5572]])

In [ ]:
x = torch.randn(2, 5, 4, 2)
print(x)
x_diag = torch.diagonal(x, offset=-1, dim1=1, dim2=2)
x_diag

tensor([[[[ 1.1150,  0.7268],
          [ 1.0132,  2.2653],
          [ 0.7607, -0.1442],
          [-2.4050,  1.5867]],

         [[ 0.7313,  0.1253],
          [-0.3764,  0.3485],
          [-1.1182, -1.2629],
          [-0.6737,  0.7530]],

         [[ 1.0242, -0.7853],
          [-0.8847, -0.7856],
          [-0.3831, -0.7938],
          [ 1.2093,  0.1743]],

         [[ 0.5014,  1.1007],
          [-0.5274, -0.5539],
          [-1.9334,  0.4514],
          [-0.2509,  1.1227]],

         [[ 1.0257, -0.2839],
          [ 0.3679,  1.0930],
          [-1.2663,  1.1975],
          [-0.1507, -1.7513]]],


        [[[ 1.3166,  0.7330],
          [ 0.1059,  0.9325],
          [-1.5847, -0.2205],
          [ 1.1543,  0.2313]],

         [[-0.8308, -0.2942],
          [ 0.5868,  0.5286],
          [-1.7182,  0.0350],
          [-0.2142,  0.1304]],

         [[ 0.5006, -0.3945],
          [-0.5627, -0.8120],
          [ 1.1871, -0.4593],
          [ 0.7619,  0.7612]],

         [[-0.4613, -1

tensor([[[ 0.7313, -0.8847, -1.9334, -0.1507],
         [ 0.1253, -0.7856,  0.4514, -1.7513]],

        [[-0.8308, -0.5627, -0.1136, -0.0692],
         [-0.2942, -0.8120,  0.6650, -0.9193]]])

## tensor.T

In [ ]:
x

tensor([[[-1.7238,  1.0210, -0.1511,  0.1328],
         [-0.3938, -0.6465, -0.5335,  1.9424],
         [ 1.8306,  0.9189, -1.3164,  1.0738]],

        [[ 2.1736, -1.2611, -0.5840,  0.0161],
         [-0.7125,  0.0446,  1.8229, -1.0388],
         [ 0.4359, -0.8504,  0.4203,  0.5563]]])

In [ ]:

print(x.shape)
print(x.T.shape)
x.T


torch.Size([2, 3, 4])
torch.Size([4, 3, 2])


tensor([[[-1.7238,  2.1736],
         [-0.3938, -0.7125],
         [ 1.8306,  0.4359]],

        [[ 1.0210, -1.2611],
         [-0.6465,  0.0446],
         [ 0.9189, -0.8504]],

        [[-0.1511, -0.5840],
         [-0.5335,  1.8229],
         [-1.3164,  0.4203]],

        [[ 0.1328,  0.0161],
         [ 1.9424, -1.0388],
         [ 1.0738,  0.5563]]])

## tensor.T

In [ ]:
x = torch.tensor([[[1, 2, 3, 4, 5], [6,7,8,9,10], [11,12,13,14,15]], [[16, 17, 18, 19, 20], [21,22,23,24,25], [26,27,28,29,30]]])

In [ ]:
print(x.shape)
x

torch.Size([2, 3, 5])


tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]],

        [[16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]])

In [ ]:
print(x.T.shape)
x.T

torch.Size([5, 3, 2])


tensor([[[ 1, 16],
         [ 6, 21],
         [11, 26]],

        [[ 2, 17],
         [ 7, 22],
         [12, 27]],

        [[ 3, 18],
         [ 8, 23],
         [13, 28]],

        [[ 4, 19],
         [ 9, 24],
         [14, 29]],

        [[ 5, 20],
         [10, 25],
         [15, 30]]])

## permute

In [ ]:
print(x.permute(2, 1, 0))

tensor([[[ 1, 16],
         [ 6, 21],
         [11, 26]],

        [[ 2, 17],
         [ 7, 22],
         [12, 27]],

        [[ 3, 18],
         [ 8, 23],
         [13, 28]],

        [[ 4, 19],
         [ 9, 24],
         [14, 29]],

        [[ 5, 20],
         [10, 25],
         [15, 30]]])


In [ ]:
x

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]],

        [[16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]])

In [ ]:
x.stride()

(15, 5, 1)

In [ ]:
y = x.permute(2, 0, 1)
print(y.shape)
print(y.stride())
y

torch.Size([5, 2, 3])
(1, 15, 5)


tensor([[[ 1,  6, 11],
         [16, 21, 26]],

        [[ 2,  7, 12],
         [17, 22, 27]],

        [[ 3,  8, 13],
         [18, 23, 28]],

        [[ 4,  9, 14],
         [19, 24, 29]],

        [[ 5, 10, 15],
         [20, 25, 30]]])

In [ ]:
x

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]],

        [[16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]])

In [ ]:
y.shape

torch.Size([5, 2, 3])

In [ ]:
y.is_contiguous()

False

In [ ]:
y.storage_offset()

0

In [ ]:
x.stride()

(15, 5, 1)

In [ ]:
y.stride()

(1, 15, 5)

If you have a one element tensor, use ``.item()`` to get the value as a
Python number


In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0980])
0.09796144813299179


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

## The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.dtype, z.device)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
    print(z.device)

tensor([1.0980], device='cuda:0')
torch.float32 cuda:0
tensor([1.0980], dtype=torch.float64)
cuda:0


In [ ]:
print(z.to("cpu").dtype)

torch.float32


In [ ]:
print(z.to("cpu").device)

cpu
